### ISSUE TITLE
List commands

### ISSUE THREAD

**Issue by Logerfo** [abhinavk99/fortnite-bot#1]
Use @botfather to set the bot commands, through the `/setcommands` command.

By the way, the bot is not working for me.

**Comment by abhinavk99** [comment]
Hello Logerfo, thank you for your feedback, however I didn't add the bot commands to Botfather because all the commands I have take in an argument (i.e. /user putusernamehere), and Botfather only supports commands that don't take one (i.e. /example).

Also, I run the bot locally on my laptop using pm2, so it'll work during the daytime, when I have my laptop turned on. I had the bot hosted on Heroku earlier, but Heroku only provides 1000 free hours each month and my other bot, CryptoBot, takes up 750 hours each month, so I stopped remote hosting this one. I apologize for the inconvenience, but I'm thinking about buying a Raspberry Pi to host my bots on 24/7. I'm not sure if I will though.

**Comment by Logerfo** [comment]
You can run two bots in the same heroku instance. In python, you can call this script in your procfile: 
```py
import first_bot
import second_bot

first.start()
second.start()
```
I suppose you can do the same in js.

**Comment by abhinavk99** [comment]
Thank you for the information, I'll look into that.
